### ISSUE TITLE
Any way to reduce the space between logo and sidebar tab?

### ISSUE THREAD

**Issue by ShixiangWang** [RinteRface/argonDash#12]
![image](https://user-images.githubusercontent.com/25057508/54673320-f9a16f80-4b34-11e9-9452-de5a3fac90a6.png)

There is too much space between them, any ideas to reduce the space or increase the size of logo?

**Comment by DivadNojnarg** [comment]
Do you mean like this?

![Capture d’écran 2019-03-20 à 11 59 09](https://user-images.githubusercontent.com/18291543/54679469-a5cc6180-4b07-11e9-93f5-0f865e84a01a.png)

This will be ugly if test has not the same length between tabs.

**Comment by ShixiangWang** [comment]
I mean reducing the red region

![image](https://user-images.githubusercontent.com/25057508/54679837-49873300-4b43-11e9-8308-56949f95272f.png)

**Comment by DivadNojnarg** [comment]
Please try download from devtools and let me know if its ok for you:
```r
devtools::install_github("RinteRface/argonDash")
```

**Comment by ShixiangWang** [comment]
@DivadNojnarg It works, thanks.
