### ISSUE TITLE
Font Awesome Icons

### ISSUE THREAD

**Issue by Morais14** [RinteRface/argonDash#16]
It's possible to use font awesome icons inside argonTabSet and argonInfoCard?

**Comment by DivadNojnarg** [comment]
Hi Morais, 

thanks for the report. Next time, could you please report this issue on argonR instead of argonDash (since argonIcon does not belong to argonDash) ?

Thanks you ;)

**Comment by DivadNojnarg** [comment]
Please reinstall argonR and argonDash:

```r
devtools::install_github("RinteRface/argonR")
devtools::install_github("RinteRface/argonDash")
```

**Comment by Morais14** [comment]
Many thanks Divad!

I apologize for my lack of attention in elaborating the question in the right place! ;)

**Comment by ElenaDatak** [comment]
Hi, 
Does it work with the CRAN version ? I can't find how...

**Comment by Morais14** [comment]
Hello @ElenaDatak! 
I'm using argonDash 0.2.0.90 and argonR 0.2.0.90. Cran versions are 0.1.0 for both packages.

**Comment by ElenaDatak** [comment]
Yes I tried it just after my message ;) Thanx ! But I gave up since the horizontal sidebar doesn't work, and the vertical one isn't collapsible...
