### ISSUE TITLE
add rsconnect folder to Rbuildignore

### ISSUE THREAD

**Issue by cderv** [RinteRface/argonDash#17]
Otherwise we get the folder when we install, and RStudio IDE offer to republish when opening th example with `argonDashGallery()`
![image](https://user-images.githubusercontent.com/6791940/60446251-4b23c500-9c21-11e9-8a21-80fcb1035ad5.png)

I think you just need to add a lines in Rbuildignore to ignore `inst/examples/rsconnect`

**Comment by DivadNojnarg** [comment]
You're right. I forgot to add it.
