### ISSUE TITLE
I cannot add an argonCard in Shiny tabItem

### ISSUE THREAD

**Issue by anaidv57** [RinteRface/argonDash#18]
Hi, 

I was trying to add an argonCard in Shiny tabItem. Is it not possible?

Kind regards, 
Ana

**Comment by anaidv57** [comment]
I was trying to do something like this:

        tabItem(tabName = "other",
                h2("other"),
                argonDashPage(
                  body = argonDashBody(
                    argonRow( argonCard(
                      title = "New project using one file",
                      src = "http://www.google.com",
                      hover_lift = TRUE,
                      shadow = TRUE,
                      shadow_size = NULL,
                      hover_shadow = FALSE,
                      border_level = 0,
                      icon = "app",
                      status = "info",
                      background_color = NULL,
                      gradient = FALSE, 
                      floating = FALSE,
                      width = 2,
                      "This is the content"
                    )
                    )
                  )
                )
        )

**Comment by DivadNojnarg** [comment]
Hi,
can you provide my the whole code please? Thanks
