### ISSUE TITLE
Sidebar tab doesn't work when published to shinyapps.io

### ISSUE THREAD

**Issue by nicolasgomasjaya** [RinteRface/argonDash#23]
I completely copy your example code that I get from https://rdrr.io/cran/argonDash/src/inst/examples/app.R and try to publish it.
Here is the link https://nicolasgomasjaya.shinyapps.io/test .
Everything works perfectly fine until it get published to shinyapps.io.
I don't know how to solve this.

**Comment by DivadNojnarg** [comment]
What version of shiny are you currently using? In 1.4.0 there are breaking changes regarding Bootstrap and jQuery. This might be the problem since argonDash was not update since.

**Comment by nicolasgomasjaya** [comment]
Thanks for your response, but I am using shiny version 1.3.2.

**Comment by DivadNojnarg** [comment]
Well. In that case I will Check what happens on shiny apps.io. Do you have any warning or error in the JavaScript console?

**Comment by nicolasgomasjaya** [comment]
There is no error at all in the Rstudio. I can run the apps locally and it is perfect. The only problem is when it get published in shinyapps.io, the sidebar menu weirdly doesn't work.
I am currently making a demo of my project with argon dashboard. I just want to say that I really admire your work, and I hope I can provide you information to fix this issue.
Thanks man.

**Comment by DivadNojnarg** [comment]
Ok I see: if you are using argonDash from CRAN, please install the dev version instead:
```r
devtools::install_github("RinteRface/argonR")
devtools::install_github("RinteRface/argonDash")
```

and redeploy your app. I acknowledge this is misleading. Initially I planned to push the new version on CRAN during the summer but did not have time yet.

**Comment by nicolasgomasjaya** [comment]
Hi David, I tried to reinstall the packages as you instructed and it solves the issue. Thank you very much, really appreciate it.
