### ISSUE TITLE
argonDash/inst/examples/ -  sidebar

### ISSUE THREAD

**Issue by anaidv57** [RinteRface/argonDash#5]
Hi, 

I executed the app.R (argonDash/inst/examples/)  and the sidebar is not loading.

Kind regards, 
Anaid Villamizar
![sidebar](https://user-images.githubusercontent.com/31296172/51545783-a2e02800-1e5a-11e9-860f-f769c531f1f2.PNG)

**Comment by anaidv57** [comment]
The same thing happens when I use argonDashGallery()

**Comment by DivadNojnarg** [comment]
Hi,
I cannot reproduce your issue. What web browser are you using? Could you run `sessionInfo()`please? is it the GitHub version or the CRAN version?

**Comment by aephidayatuloh** [comment]
Did you use RStudio's default window or internet explorer/edge to view the app?

**Comment by DivadNojnarg** [comment]
<img width="1169" alt="capture d ecran 2019-01-30 a 12 39 52" src="https://user-images.githubusercontent.com/18291543/51979018-40a3aa80-248c-11e9-889c-13fc6491ee90.png">

RStudio's default window or chrome, safari, firefox, opera, brave ... But forget about internet explorer and Edge.

**Comment by siddbhatia** [comment]
Hi,

I can successfully get the examples running, but when I use
```r
argonSidebarMenu(
                vertical = FALSE,
```

It only makes the side bar horizontal , not the side menu  inside 
<img width="1385" alt="screen shot 2019-02-25 at 10 37 49 am" src="https://user-images.githubusercontent.com/4471954/53315547-c0852f00-38e9-11e9-9d7c-c60534fc6c5a.png">


I even tried using a navBarMenu inside the sidebar , which successfully makes all the items horizontal , but leads to loss of reactivity on tabs.

Is there a solution ? Something like `vertical = FALSE` for `argonSidebarMenu` ?

**Comment by DivadNojnarg** [comment]
Humm, I am not able to reproduce this bug. Are you using the CRAN or the devel version. Indeed, the horizontal feature only works for the development release, not the CRAN one:

```r
devtools::install_github("RinteRface/argonDash")
```

**Comment by siddbhatia** [comment]
> Humm, I am not able to reproduce this bug. Are you using the CRAN or the devel version. Indeed, the horizontal feature only works for the development release, not the CRAN one:
> 
> ```r
> devtools::install_github("RinteRface/argonDash")
> ```

Yes that worked out fine , there was an additional fix on vertical/horizontal on navbar class (argonDashSidebar). 
Keep up the good work , I never thought my shiny dashboards would look so beautiful.

**Comment by jbixon13** [comment]
It appears I am running into this same issue even though I am using the Github version of argonDash. I've attached my sessionInfo and a screenshot of the sidebar (taken on Firefox but same issue appears on Chrome); I would appreciate any help. 

![image](https://user-images.githubusercontent.com/32110237/60400117-91075d00-9b3d-11e9-83c7-b327b77d84e1.png)

![image](https://user-images.githubusercontent.com/32110237/60400126-b98f5700-9b3d-11e9-821a-6598e260c9c1.png)

**Comment by jbixon13** [comment]
Aaaaand as soon as I send that I see argonDash is using 0.1.0. Could be the issue, but I definitely was using 0.2.0.9 yesterday; will try updating to resolve.

**Comment by jbixon13** [comment]
Confirmed not working after updating to Github version again

**Comment by DivadNojnarg** [comment]
Hi, could you send me your sessionInfo again as well as a minimal example reproducing the bug. Thanks.

**Comment by jbixon13** [comment]
SessionInfo:
![image](https://user-images.githubusercontent.com/32110237/60478740-863dec80-9c51-11e9-8d8e-6fa2936f084e.png)

I'm seeing two behaviors based on slightly different setups: 
Example 1: 
```
shinyUI(
  argonDashPage(title = 'Sync the City',
                description = 'Testing',
                header = argonDashHeader(color = 'primary', separator = TRUE),
                sidebar = argonDashSidebar(vertical = FALSE,
                                           id = 'sidebar',
                                           argonSidebarHeader(title = 'Main Menu'),
                                           
                                           argonSidebarMenu(
                                             argonSidebarItem(tabName = 'landing_page', 'Landing Page'),
                                             argonSidebarItem(tabName = 'map', 'Map'),
                                             argonSidebarItem(tabName = 'network', 'Network')
                                             )
                                           )
  )
)
```

Example 1 output: 
![image](https://user-images.githubusercontent.com/32110237/60479643-88ee1100-9c54-11e9-93c1-830257088d64.png)

Example 2: 
```
shinyUI(
  argonDashPage(title = 'Sync the City',
                description = 'Testing',
                header = argonDashHeader(color = 'primary', separator = TRUE),
                sidebar = argonDashSidebar(vertical = FALSE,
                                           id = 'sidebar',
                                           size = "md",
                                           brand_url = "http://www.google.com",

                                           argonSidebarHeader(title = 'Main Menu'),
                                           
                                           argonSidebarMenu(
                                             
                                             argonSidebarItem(tabName = "landing_page", "Landing Page"),
                                             argonSidebarItem(tabName = "map_UI", "Map"),
                                             argonSidebarItem(tabName = "network_UI", "Network")
                                           )
                )
  )
)
```

Example 2 output: 
![image](https://user-images.githubusercontent.com/32110237/60479993-e20a7480-9c55-11e9-8f3c-187796e58967.png)

The only difference between the inputs is in example 2 where size and brand_url are declared. If either one or the other of these are commented out they revert to the larger buttons seen in the example 1 output (even though size is using the default input of medium). Neither seems to be the expected output.

**Comment by rdornas** [comment]
Hello! When I run `argonDashGallery()` I get the following error:

```
Error in system.file(paste0("examples/app.R"), package = "argonDash",  : 
  no file found
```

It seems that the problem is that the `app.R` file is in another folder in examples, called `gallery`. That way, you might want to change the `argonDashGallery()` function to search for the `app.R` in `examples/gallery/app.R`.
