### ISSUE TITLE
Access current tab selection

### ISSUE THREAD

**Issue by ghost** [RinteRface/argonDash#7]
Hi,
I tried to access the current tab selection by running `input$sidebar`, `sidebar` being the id of the sidebar used in `argonDashSidebar` but it did not work. Is this a bug?

**Comment by DivadNojnarg** [comment]
Hi, 

There is no input associated with the sidebar or tabCard. Therefore this behavior is expected. For the moment you could create a JavaScript code to set a Shiny.onInputChange. It won’t  work with Shinytest.

**Comment by ghost** [comment]
Thanks for the suggestion, the workaround works.

**Comment by OGuggenbuehl** [comment]
Would you be willing to post an example of the workaround?

**Comment by ghost** [comment]
Hey @OGuggenbuehl,

Basically I added the following JS code to `argonDashBody`
```
tags$script( "$(document).on('click', function(event) {
              Shiny.onInputChange('activeTab', $('.active').data().value);});")
```
Which creates `input$activeTab` containing the id of the active tab. 

This trick only works after the user clicks anywhere on page, I couldn't get `Shiny.onInputChange` to work without that.

Let me know if you still need help.
