### ISSUE TITLE
Tabs not working in shinyapps.io

### ISSUE THREAD

**Issue by aephidayatuloh** [RinteRface/argonDash#8]
Hi,
Thank you for this great package. Currently I'm developing an app using argonDash.

When I developed the app on my local machine, the app worked properly all the way that I want. But after deployed it to shinyapps.io, the tabs does not display the contents. Only the first tab's content that displayed on the browser. When I clicked the other tabs, it's content does not appear.

Here is my repo https://github.com/aephidayatuloh/stk211 and this is my app https://analyticastudio.shinyapps.io/stk211.

Kindly need your advice.
Thanks

EDIT: I also changed the argon.min.css to fit my needes.

**Comment by DivadNojnarg** [comment]
Hi,

Thanks for your interest in the package. Downloading the dev version from GitHub should solve your problem. 

devtools::install_github(...)

**Comment by aephidayatuloh** [comment]
Thank you so much, it worked!
